
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlwvqbrtdzwrcwelyylv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsd3ZxYnJ0ZHp3cmN3ZWx5eWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTc4NjAsImV4cCI6MjA2NTc5Mzg2MH0.GmRCWAoYJgXSKbxxRWPo_vRhEXVMmE73xfQswXtpE_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
